### ISSUE TITLE
Rename repo and package and remove "UserDomain"

### ISSUE THREAD

**Issue by rrrene** [atlas-engine/Client.ts#1]
Wie @moellenbeck richtigerweise angemerkt hat, sollten wir das Wort "ConsumerAPI", das keiner verstanden hat, nicht durch das Wort "UserDomain" ersetzen, dass keiner  verstehen wird.

Bitte das analog zu https://github.com/atlas-engine/Client.NET in `Client.ts` umbenennen. 

Beim Package `@atlas-engine/user_domain.client.http` bitte auch das `user_domain` entfernen. Das Package am Besten in `@atlas-engine/atlas_engine_client` umbenennen.

**Comment by ElRaptorus** [comment]
@rrrene done and done.
